In [1]:
documents = [ 
   "The cat sits on the mat", 
   "A feline is resting on the rug", 
   "Dogs and cats are common pets", 
   "The dog plays in the garden", 
   "Pets like cats and dogs are friendly", 
   "A kitten is a young cat", 
   "Puppies are young dogs", 
   "Animals like feline and canine are mammals" 
] 



In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer(stop_words="english")
x=vectorizer.fit_transform(documents)

words=vectorizer.get_feature_names_out()
x

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 29 stored elements and shape (8, 21)>

In [69]:
from sklearn.decomposition import TruncatedSVD

svd=TruncatedSVD(n_components=2,random_state=42)
x_Red=svd.fit_transform(x)
x_Red

array([[ 9.42000972e-02,  6.11617660e-01],
       [ 5.82846597e-02, -1.13293503e-01],
       [ 8.07394555e-01, -2.35446932e-01],
       [-3.30563382e-16,  7.11821440e-16],
       [ 8.27011046e-01, -2.81196890e-01],
       [ 2.53285295e-01,  8.00981588e-01],
       [ 5.32530514e-01,  3.96885957e-01],
       [ 2.12098976e-01, -2.00804389e-01]])

In [70]:
from sklearn.preprocessing import normalize
word_vectors=normalize(svd.components_.T)
word_vectors

array([[ 6.36695659e-01, -7.71115191e-01],
       [ 6.36695659e-01, -7.71115191e-01],
       [ 1.90545880e-01,  9.81678291e-01],
       [ 9.27606910e-01, -3.73557788e-01],
       [ 9.36930336e-01, -3.49516160e-01],
       [-1.93041658e-16,  4.29173045e-16],
       [ 9.99812122e-01, -1.93835151e-02],
       [ 5.44013645e-01, -8.39076370e-01],
       [ 9.17009683e-01, -3.98864941e-01],
       [-1.89755457e-16,  4.01868928e-16],
       [ 2.39969327e-01,  9.70780471e-01],
       [ 8.64451591e-01, -5.02716069e-01],
       [ 6.36695659e-01, -7.71115191e-01],
       [ 1.19534564e-01,  9.92830040e-01],
       [ 9.27606910e-01, -3.73557788e-01],
       [-1.89755457e-16,  4.01868928e-16],
       [ 7.23770420e-01,  6.90040854e-01],
       [ 3.73115893e-01, -9.27784744e-01],
       [ 3.73115893e-01, -9.27784744e-01],
       [ 1.19534564e-01,  9.92830040e-01],
       [ 4.61172319e-01,  8.87310595e-01]])

In [71]:
query="cat"
query_idx=list(words).index(query)
query_vec=word_vectors[query_idx]

In [72]:
from sklearn.metrics.pairwise import cosine_similarity
similarities=cosine_similarity([query_vec],word_vectors)[0]
similarities

array([-6.35667309e-01, -6.35667309e-01,  1.00000000e+00, -1.89961897e-01,
       -1.64584211e-01,  3.84526569e-16,  1.71481704e-01, -7.20043499e-01,
       -2.16824637e-01,  3.58348882e-16,  9.98719280e-01, -3.28787763e-01,
       -6.35667309e-01,  9.97416516e-01, -1.89961897e-01,  3.58348882e-16,
        8.15309597e-01, -8.39690446e-01, -8.39690446e-01,  9.97416516e-01,
        9.58928034e-01])

In [73]:
import numpy as np

top_indices=np.argsort(similarities)[::-1]

for i in top_indices[0:4]:
    print(words[i],similarities[i])

cat 1.0000000000000002
kitten 0.9987192801634937
mat 0.9974165158046276
sits 0.9974165158046276
